export const LIKE_PRODUCT = "LIKE_PRODUCT";
export const DISLIKE_PRODUCT = "DISLIKE_PRODUCT";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";